DB CREATION

CREATE DATABASE LIBRARY_MANAGEMENT;
USE LIBRARY_MANAGEMENT;
CREATE TABLE LIBRARIAN(
	LIB_ID INT (10) auto_increment PRIMARY KEY,
    NAME VARCHAR (20),
    PHONE bigint (10),
    EMAIL varchar(30),
    ADDRESS VARCHAR(100));
CREATE TABLE BOOKS(
	BOOK_ID INT (10) auto_increment primary KEY,
    ISBN BIGINT(15),
    TITLE VARCHAR(50),
    AUTHOR VARCHAR(25),
    DOMAIN VARCHAR(20),
    PUB_YEAR INT(10),
    AVAILABLE_QTY INT(5),
    STOCK_QTY INT (5));
CREATE TABLE USERS(
	USER_ID INT (10) auto_increment primary KEY,
    NAME VARCHAR(25),
    ADDRESS VARCHAR(100),
    PHONE BIGINT(10),
    EMAIL VARCHAR(30));
CREATE TABLE STAFF(
	STAFF_ID INT (10) auto_increment primary KEY,
    NAME VARCHAR(25),
    DEPARTMENT varchar(20),
    ADDRESS VARCHAR(100),
    PHONE BIGINT(10),
    EMAIL VARCHAR(30));
CREATE TABLE ISSUED(
	ISSUE_ID INT(10) auto_increment primary KEY,
    BOOK_ID INT(10),
    USER_ID INT(10),
    ISSUE_DATE date,
    DUE_IN DATE,
    RETURN_DATE DATE,
    RETURN_STATUS VARCHAR(14) default 'NOT RETURNED',
    FOREIGN KEY(BOOK_ID) references BOOKS(BOOK_ID) ON DELETE NO ACTION,
    FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID) ON DELETE NO ACTION);
CREATE TABLE FINES(
	FINE_ID INT(10) auto_increment primary key,
    ISSUE_ID INT(10),
    USER_ID INT(10),
    AMOUNT DOUBLE(4,2),
    REASON VARCHAR(30) DEFAULT 'RETURN DELAY',
    foreign key(ISSUE_ID) references ISSUED(ISSUE_ID) ON DELETE NO ACTION,
    FOREIGN KEY(USER_ID) REFERENCES USERS(USER_ID) ON DELETE CASCADE);
CREATE TABLE LOGINS(
	USER_TYPE VARCHAR(20),
    ID INT(10),
    PASSWORD VARCHAR(20),
    primary key(USER_TYPE,ID));